# Generated by Django 4.2.13 on 2024-07-14 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=25, unique=True)),
                ('description', models.TextField(null=True)),
                ('excepted_value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('value', models.FloatField(default=0)),
                ('depense', models.BooleanField(default=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.domain')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.gestion')),
            ],
        ),
        migrations.CreateModel(
            name='RelationToParentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion.domain')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.gestion'),
        ),
        migrations.AddField(
            model_name='domain',
            name='relation_to_parent_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.relationtoparentdomain'),
        ),
    ]
