# Generated by Django 4.2.13 on 2024-07-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_dateinterval_end_alter_dateinterval_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateinterval',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dateinterval',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
